package de.tum.in.ase.eist;

import de.tum.in.ase.eist.Controller.Controller;
import de.tum.in.ase.eist.Model.DatabaseHelper;
import de.tum.in.ase.eist.Model.MFT;
import de.tum.in.ase.eist.Model.TransactionLog;
import de.tum.in.ase.eist.View.TextView;

import java.util.List;

/*************************
 * DO NOT EDIT THIS FILE *
 *************************/


public class TradingApplication {

    public static void main(String[] args) {
        DatabaseHelper databaseHelper = new DatabaseHelper("jdbc:sqlite:mft.db");
        databaseHelper.initializeDatabase();

		TransactionLog log = new TransactionLog();
        Controller controller = new Controller(databaseHelper, log);

        List<MFT> mfts = controller.getMFTs();

		// stock some MFTs
        if (mfts.isEmpty()) {
			MFT mft = new MFT("Ape", "Do not", 1010.10);
			controller.addMFT(mft);
			mft = new MFT("Monkey", "right click", 2020.20);
			controller.addMFT(mft);
            mfts = controller.getMFTs();
        }

        TextView mainView = new TextView(controller, mfts);
        controller.registerClient(mainView);
        mainView.run();

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            databaseHelper.closeConnection();
            System.out.println("Database connection closed.");
        }));
        }
}

