package de.tum.in.ase.eist.Model;

/*************************
 * DO NOT EDIT THIS FILE *
 *************************/

// Maybe fungible token
public class MFT extends Observable {
	private static int nextID = 1;
    private int id;
    private String name;
    private String description;
    private double price;


    public MFT(int id, String name, String description, double price) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.price = price;
    }

    public MFT(String name, String description, double price) {
        this.id = nextID++;
        this.name = name;
        this.description = description;
        this.price = price;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public double getPrice() {
        return price;
    }

    @Override
    public String toString() {
        return "MFT{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", price=" + price +
                '}';
    }
}
