package de.tum.in.ase.eist.Model;

import de.tum.in.ase.eist.View.Observer;
import java.util.ArrayList;
import java.util.List;

/*************************
 * DO NOT EDIT THIS FILE *
 *************************/

public abstract class Observable {

    private List<Observer> observers = new ArrayList<>();

    public void notifyObservers() {
        for (Observer observer : observers) {
            observer.update();
        }
    }

    public List<Observer> getObservers() {
        return observers;
    }

    public void addObserver(Observer observer) {
        observers.add(observer);
    }

    public void addAllObservers(List<Observer> observers) {
        this.observers.addAll(observers);
    }
}

