package de.tum.in.ase.eist.Model;

/*************************
 * DO NOT EDIT THIS FILE *
 *************************/

public class Transaction {
	private final int sellerId;
	private final int buyerId;
	private final int MFTId;
	private final double price;

	public Transaction(int sellerId, int buyerId, int MFTId, double price) {
		this.sellerId = sellerId;
		this.buyerId = buyerId;
		this.MFTId = MFTId;
		this.price = price;
	}

	public int getSellerId() {
		return sellerId;
	}

	public int getBuyerId() {
		return buyerId;
	}

	public int getMFTId() {
		return MFTId;
	}

	public double getPrice() {
		return price;
	}
}
