package de.tum.in.ase.eist.View;

import java.util.Scanner;

/*************************
 * DO NOT EDIT THIS FILE *
 *************************/

public class ScannerWrapper {
    private Scanner scanner;

    public ScannerWrapper(Scanner scanner) {
        this.scanner = scanner;
    }

    public String nextLine() {
        return scanner.nextLine();


    }

    public int nextInt() {
        return scanner.nextInt();

    }


    public double nextDouble() {
        return scanner.nextDouble();
    }


}
